# fly.toml app configuration file generated for brewnet-api on 2025-02-25T16:31:12+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brewnet-api'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
