app = "brewnet-api"
primary_region = "sin"  # Singapore region, change as needed

[env]
  PORT = "5000"
  NODE_ENV = "production"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1 