services:
  - type: web
    name: brewnet-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: RESEND_API_KEY
        sync: false 